
version: '3.1'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest_admin
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_AUTHENTICATION_PLUGIN: 'mysql_native_password'
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: nest
    ports:
      - "27017:27017"
